services:
  app_php81:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: getcare_app_php81
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - getcare_network
    depends_on:
      ollama:
        condition: service_started

  ollama:
    image: ollama/ollama
    container_name: getcare_ollama
    restart: unless-stopped
    ports:
      - "11435:11434"
    volumes:
      - ./ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
      
    networks:
      - getcare_network 
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  getcare_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local