services:
  app:
    build:
      context: . # Now docker-compose.yml is in get-care, so context is the current directory
      dockerfile: Dockerfile
    container_name: getcare_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html # Mount the current directory (get-care)
    networks:
      - getcare_network
    depends_on:
      db:
        condition: service_started
    command: sh -c "groupadd -g 1001 getcare && usermod -a -G getcare www-data || true && chown -R www-data:www-data storage bootstrap && chmod -R 775 storage bootstrap && php-fpm"
  nginx:
    image: nginx:alpine
    container_name: getcare_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html # Mount the current directory (get-care)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - getcare_network

  db:
    image: postgres:13-alpine
    container_name: getcare_db
    restart: unless-stopped
    ports:
      - "5449:5432"
    environment:
      POSTGRES_DB: getcare_db
      POSTGRES_USER: getcare_user
      POSTGRES_PASSWORD: getcare_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - getcare_network

networks:
  getcare_network:
    driver: bridge

volumes:
  db_data:
    driver: local
